### ISSUE TITLE
Build map of logical steps

### ISSUE THREAD

**Issue by lostmarinero** [codeforamerica/ShotBot#57]
- [ ] Sketch current flow #60
- [ ] Check flow against CDC Logic Specification document #61
- [ ] Adjust github issues to account for steps #62
